#include <WiFi.h>
#include <WebServer.h>
#include <DHT.h>

// --- CONFIGURAÇÃO DO WIFI ---
const char* ssid = "AndroidAP46EC";
const char* password = "pie31415926535";

// --- CONFIGURAÇÃO DO DHT ---
#define DHTPIN 2         
#define DHTTYPE DHT11     
DHT dht(DHTPIN, DHTTYPE);

// --- SERVIDOR ---
WebServer server(80);

// Função para conectar ao Wi-Fi
String conectar_wifi(const char* ssid, const char* senha) {
  WiFi.begin(ssid, senha);
  Serial.print("Conectando-se ao WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("Conectado. IP: ");
  Serial.println(WiFi.localIP());
  return WiFi.localIP().toString();
}

// Fornece a página HTML é uma função que está no final do codigo


// Rota que envia temperatura e umidade reais
void fornecer_temperatura_e_humidade() {
  server.on("/tmp_e_umd", HTTP_GET, []() {
    float temperatura = dht.readTemperature();
    float umidade = dht.readHumidity();

    // Verifica se leitura falhou
    if (isnan(temperatura) || isnan(umidade)) {
      server.send(500, "application/json", "{\"erro\": \"Falha na leitura do sensor\"}");
      return;
    }

    String json = "{\"tmp\":" + String(temperatura) + ",\"umd\":" + String(umidade) + "}";
    server.send(200, "application/json", json);
  });
}

//______PRINCIPAL________
void setup() {
  Serial.begin(115200);
  dht.begin();

  String IP = conectar_wifi(ssid, password);
  fornecer_pagina(IP);
  fornecer_temperatura_e_humidade();
  server.begin();
}

void loop() {
  server.handleClient();
}


String html =
"\n"
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Painel | Controle</title>\n"
"    <style>\n"
"        body{\n"
"    margin: 0px;\n"
"    }\n"
"\n"
"    main{\n"
"        display: flex;\n"
"        height: 100vh;\n"
"        width: 100vw;\n"
"    }\n"
"\n"
"\n"
"    #Painel{\n"
"        width: 100%;\n"
"        padding: 50px 10px 0px 10px;\n"
"    }\n"
"\n"
"    h3{\n"
"        margin-left:20%;\n"
"        font-family: \"Arial\";\n"
"    }\n"
"\n"
"    #infos{\n"
"        display: flex;\n"
"        padding-left:10% ;\n"
"        gap: 20%;\n"
"    }\n"
"\n"
"    #temperatura{\n"
"        text-align: center;\n"
"        font-family: \"Arial\";\n"
"    }\n"
"\n"
"    #umidade{\n"
"        text-align: center;\n"
"        font-family: \"Arial\";\n"
"    }\n"
"\n"
"    #barraTMP{\n"
"        height: 100px;\n"
"        width: 100px;\n"
"        border-radius: 50%;\n"
"        border: 5px solid white;\n"
"        background: conic-gradient(#3498db 5deg , white 0deg);\n"
"        transform: rotate(-90deg);\n"
"        display: flex;\n"
"        align-items: center;\n"
"        justify-content: center;\n"
"        \n"
"    }\n"
"\n"
"    #barraUMD{\n"
"        color: rgb(0, 217, 255);\n"
"        height: 100px;\n"
"        width: 100px;\n"
"        border-radius: 50%;\n"
"        border: 5px solid white;\n"
"        background: conic-gradient(#3498db 5deg , white 0deg);\n"
"        transform: rotate(-90deg);\n"
"        display: flex;\n"
"        align-items: center;\n"
"        justify-content: center;\n"
"    }\n"
"\n"
"    .circulo{\n"
"        width: 85px;\n"
"        height: 85px;\n"
"        border-radius: 50%;\n"
"        background-color: white;\n"
"    }\n"
"\n"
"    #nav {\n"
"        display: flex;\n"
"        flex-direction: column;\n"
"        align-items: center;\n"
"        width: 90px;\n"
"        height: 100vh;\n"
"        background-color: rgb(24, 179, 3); \n"
"        box-shadow: 5px 0px 30px rgba(0, 0, 0, 0.3);\n"
"        padding: 16px 0px 0px 0px;\n"
"        gap: 16px;\n"
"        overflow-y: auto;  \n"
"        scroll-behavior: smooth; \n"
"    }\n"
"\n"
"\n"
"    #nav::-webkit-scrollbar {\n"
"        width: 6px; \n"
"    }\n"
"\n"
"    #nav::-webkit-scrollbar-track {\n"
"        background: rgb(24, 179, 3); \n"
"        border-radius: 10px; \n"
"    }\n"
"\n"
"    #nav::-webkit-scrollbar-thumb {\n"
"        background-color: #27ae60; \n"
"        border-radius: 10px; \n"
"        border: 2px solid rgb(24, 179, 3); \n"
"    }\n"
"\n"
"    #nav::-webkit-scrollbar-thumb:hover {\n"
"        background-color: #2ecc71; \n"
"    }\n"
"\n"
"\n"
"\n"
"    .planta{\n"
"        width: calc(100% - 10px);\n"
"        height: 50px;\n"
"        display: flex;\n"
"        flex-direction: column;\n"
"        align-items: center;\n"
"        cursor: pointer;\n"
"        padding: 5px;\n"
"        font-family: \"arial\";\n"
"        font-size: 12px;\n"
"    }\n"
"\n"
"    .planta:hover{\n"
"        background-color: rgb(22, 158, 4);\n"
"    }\n"
"\n"
"    .planta div{\n"
"        display: flex;\n"
"        justify-content: center;\n"
"        align-items: center;\n"
"        width: 40px;\n"
"        height: 40px;\n"
"        background-color:rgb(122, 241, 106);\n"
"        border-radius: 50%;\n"
"    }\n"
"\n"
"    #infos_planta{\n"
"        padding-left: 10% ;\n"
"    }\n"
"\n"
"    h2{\n"
"        font-family: \"Segoe Script\", \"Lucida Handwriting\", cursive;\n"
"        font-size: 25px;\n"
"        color: rgb(7, 54, 1);\n"
"        margin-bottom: 0px;\n"
"        padding-left: 15%;\n"
"    }\n"
"\n"
"    #Painel i{\n"
"        padding-left: 15%;\n"
"    }\n"
"\n"
"    #infos_planta p{\n"
"        margin-bottom: 0px;\n"
"        padding-bottom: 0px;\n"
"    }\n"
"\n"
"    .cadas{\n"
"        display: flex;\n"
"        opacity: 0;\n"
"        pointer-events: none;\n"
"        position: fixed;\n"
"        flex-direction: column;\n"
"        background-color: rgb(24, 179, 3);\n"
"        width: 50%;\n"
"        max-width: 500px;\n"
"        border-radius: 5px;\n"
"        padding: 10px;\n"
"        gap: 10px;\n"
"        font-family: 'Arial';\n"
"        transition: 0.3s ease;\n"
"    }\n"
"\n"
"    .mostrado{\n"
"        display: flex;\n"
"        pointer-events: auto;\n"
"    }\n"
"\n"
"    .cadas input{\n"
"        display: flex;\n"
"        border-radius: 5px;\n"
"        height: 20px;\n"
"        padding: 3px;\n"
"        border: none;\n"
"    }\n"
"\n"
"    #tipos{\n"
"        display: flex;\n"
"        flex-direction: row;\n"
"        justify-content: space-around;\n"
"    }\n"
"\n"
"    #btn{\n"
"        display: flex;\n"
"        justify-content: end;\n"
"    }\n"
"\n"
"    #botao{\n"
"        width: 100px;\n"
"        height: 20px;\n"
"        cursor: pointer;\n"
"        color: rgb(221, 249, 194);\n"
"        background-color: rgb(45, 216, 22);\n"
"        transition: 0.3s ease;\n"
"    }\n"
"\n"
"    #botao:hover{\n"
"        background-color: rgb(35, 249, 7);\n"
"    }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <main>\n"
"        <div id=\"nav\">\n"
"            \n"
"        </div>\n"
"        <div id=\"Painel\">\n"
"            <h2></h2>\n"
"            <i></i>\n"
"            <p style=\"color: white;\">.</p>\n"
"            <div id=\"infos\">\n"
"                <div id=\"temperatura\">\n"
"                    <div id=\"barraTMP\"><div class=\"circulo\"></div></div>\n"
"                    <p id=\"TMP\">Temperatura: </p>\n"
"                </div>\n"
"                <div id=\"umidade\">\n"
"                    <div id=\"barraUMD\"><div class=\"circulo\"></div></div>\n"
"                    <p id=\"UMD\">Umidade: </p>\n"
"                </div>\n"
"                <div class=\"cadas\" id=\"cadast\">\n"
"                    <p>Nova planta</p>\n"
"                    <input type=\"text\" placeholder=\"Nome\" id=\"nome\">\n"
"                    <input type=\"text\" placeholder=\"Temperatura máxima\" id=\"nome_max\">\n"
"                    <input type=\"text\" placeholder=\"Temperatura mínima\" id=\"nome_min\">\n"
"                    <input type=\"text\" placeholder=\"Umidade_maxima\" id=\"nome_umd_max\">\n"
"                    <input type=\"text\" placeholder=\"Umidade_minima\" id=\"nome_umd_min\">\n"
"                    <input type=\"text\" placeholder=\"Gênero\" id=\"nome_gen\">\n"
"                    <input type=\"text\" placeholder=\"Epiteto\" id=\"nome_epitet\">\n"
"                    <div id=\"tipos\">\n"
"                        <input type=\"radio\" name=\"tipo\" id=\"1\" value=\"arvore\"><label for=\"1\">Arvore</label>\n"
"                        <input type=\"radio\" name=\"tipo\" id=\"2\" value=\"erva\"><label for=\"2\">Erva</label>\n"
"                        <input type=\"radio\" name=\"tipo\" id=\"3\" value=\"flor\"><label for=\"3\">Flor</label>\n"
"                        <input type=\"radio\" name=\"tipo\" id=\"4\" value=\"grão\"><label for=\"4\">Grão</label>\n"
"                    </div>\n"
"                    <div id=\"btn\"><input type=\"button\" id=\"botao\" value=\"Cadastrar\"></div>\n"
"                </div>\n"
"            </div>\n"
"            <div id=\"infos_planta\">\n"
"\n"
"            </div>\n"
"        </div>\n"
"    </main>\n"
"</body>\n"
"    <script>\n"
"        let tmp = 50;\n"
"        let umd = 50;\n"
"\n"
"        let plantas = [\n"
"            {nome:\"Samambaia\",tmp_max:50,tmp_min:15,umd_max:60,umd_min:40,genero:\"Nephrolepsis\",epiteto:\"exaltata\", tipo:\"erva\"}\n"
"        ];\n"
"\n"
"        const barra_tmp = document.getElementById(\"barraTMP\");\n"
"        const barra_umd = document.getElementById(\"barraUMD\");\n"
"        const displayTMP = document.getElementById(\"TMP\");\n"
"        const displayUMD = document.getElementById(\"UMD\");\n"
"        const NAV_plantas = document.getElementById(\"nav\");\n"
"        const plantas_tela = document.getElementsByClassName(\"planta\");\n"
"        const display_infos = document.getElementById(\"infos_planta\");\n"
"        const titulo = document.querySelector(\"#Painel h2\");\n"
"        const titulo_italic = document.querySelector(\"#Painel i\");\n"
"\n"
"        //define a cor do grafico em função do percentual de preenchimento dele\n"
"        function setCor(per, cor1, cor2){\n"
"            const r = Math.round(cor1[0] + (cor2[0] - cor1[0]) * per);\n"
"            const g = Math.round(cor1[1] + (cor2[1] - cor1[1]) * per);\n"
"            const b = Math.round(cor1[2] + (cor2[2] - cor1[2]) * per);\n"
"            return `rgb(${r}, ${g}, ${b})`;\n"
"        }\n"
"\n"
"        //reenderiza o grafico da temperatura\n"
"        function renderTMP( TMP, plantas, indice){\n"
"            const vermelho = [255,0,0];\n"
"            const verde_aceitavel = [24,179,3];\n"
"            const verde_ideal = [45, 236, 6];\n"
"            const azul = [0,217,255];\n"
"            \n"
"            let percentual = (TMP - plantas[indice].tmp_min) / (plantas[indice].tmp_max - plantas[indice].tmp_min);\n"
"            let angulo = percentual*180;\n"
"            let cor;\n"
"            \n"
"            if ( percentual <= 0.25){\n"
"                cor = setCor(percentual, azul, verde_aceitavel);\n"
"            } else if (percentual <= 0.5){\n"
"                cor = setCor(percentual, verde_aceitavel, verde_ideal);\n"
"            } else if (percentual <= 0.85){\n"
"                const p = 2*(percentual - 0.5);\n"
"                cor = setCor(percentual,verde_ideal, verde_aceitavel);\n"
"            } else {\n"
"                const p = 2*(percentual - 0.5);\n"
"                cor = setCor(percentual,verde_aceitavel, vermelho);\n"
"            }\n"
"            \n"
"            \n"
"            barra_tmp.style.background = \"conic-gradient( \"+cor+\" \"+angulo+\"deg, white 0deg\";\n"
"            displayTMP.style.color = cor;\n"
"            \n"
"            displayTMP.innerHTML = \"Temperatura: \"+TMP+\"°C\";\n"
"        }\n"
"\n"
"        //reenderiza o grafico da umidade\n"
"        function renderUMD( UMD, plantas, indice ){\n"
"            const vermelho = [255,0,0];\n"
"            const verde_aceitavel = [24,179,3];\n"
"            const verde_ideal = [45, 236, 6];\n"
"            const azul = [0,217,255];\n"
"            \n"
"            let percentual = (UMD - plantas[indice].umd_min) / (plantas[indice].umd_max - plantas[indice].umd_min);\n"
"            let angulo = percentual*180;\n"
"            let cor = \"blue\";\n"
"            \n"
"            barra_umd.style.background = \"conic-gradient( \"+cor+\" \"+angulo+\"deg, white 0deg\";\n"
"            displayUMD.style.color = cor;\n"
"            displayUMD.innerHTML = \"Umidade: \"+UMD+\"%\";\n"
"        }\n"
"\n"
"\n"
"        //reenderiza todas as plantas do banco de dados na barra NAV\n"
"        //recebe o argumento plantasJSON, que nao e um json , mas o objeto que resulta dele\n"
"        function render_plantas( plantasJSON ){\n"
"            console.log(plantasJSON);\n"
"            let count = -1;\n"
"            NAV_plantas.innerHTML += \"<div id='cadastrar' class='planta'>\"+\n"
"                                        \"<div>+</div>\"+\n"
"                                        \"Cadastrar\"+\n"
"                                    \"</div>\";\n"
"            let cadast = document.getElementById(\"cadast\");\n"
"            plantasJSON.forEach((planta) => {\n"
"                count++;\n"
"                let figura;\n"
"                switch (planta.tipo){\n"
"                    case \"arvore\":\n"
"                        figura = \"&#127795;\";\n"
"                        break;\n"
"                    case \"erva\":\n"
"                        figura = \"&#127807;\";\n"
"                        break;\n"
"                    case \"flor\":\n"
"                        figura = \"&#127803;\";\n"
"                        break;\n"
"                    case \"grao\":\n"
"                        figura = \"&#127793;\";\n"
"                }\n"
"                NAV_plantas.innerHTML += \"<div id='\"+count+\"' class='planta'>\"+\n"
"                                            \"<div>\"+figura+\"</div>\"+\n"
"                                            planta.nome+  \n"
"                                        \"</div>\";\n"
"            });\n"
"        }\n"
"\n"
"        //reenderiza as informações da planta escolhida, como genero e epiteto\n"
"        function render_infos_planta(plantas, indice){\n"
"            titulo.innerHTML = plantas[indice].nome;\n"
"            titulo_italic.innerHTML = plantas[indice].genero + \" \" + plantas[indice].epiteto;\n"
"            display_infos.innerHTML = \"<p>-temperatura minima: \"+plantas[indice].tmp_min+\"°C</p>\"+\n"
"                                    \"<p>-temperatura maxima: \"+plantas[indice].tmp_max+\"°C</p>\"+\n"
"                                    \"<p>-umidade minima: \"+plantas[indice].umd_min+\"%</p>\"+\n"
"                                    \"<p>-umidade maxima: \"+plantas[indice].umd_max+\"%</p>\";\n"
"        }\n"
"\n"
"        //mostra o input do cadastro na tela\n"
"        function render_cadas(){\n"
"            cadast.classList.add(\"mostrado\");\n"
"            console.log(\"clicado\");\n"
"            \n"
"        }\n"
"\n"
"        //fluxo principal do programa da tela\n"
"        let indice = 0;\n"
"        renderTMP( tmp, plantas, indice);\n"
"        renderUMD(umd, plantas, indice);\n"
"        render_plantas( plantas );\n"
"        render_infos_planta(plantas, indice);\n"
"\n"
"        //serve para adicionar os eventos para as divs .planta na tela\n"
"        for( let i = 0 ; i < plantas_tela.length; i++){\n"
"            plantas_tela[i].onclick = () => {\n"
"                indice = i;\n"
"                renderTMP(tmp, plantas,indice);\n"
"                render_infos_planta(plantas, indice);\n"
"                renderUMD(umd, plantas, indice);\n"
"            };\n"
"            if (plantas_tela[i].id === \"cadastrar\"){\n"
"                plantas_tela[i].onclick = () => {render_cadas()};\n"
"            }\n"
"        }\n"
"\n"
"        setInterval( () => {\n"
"            fetch(\"http://\" + window.location.hostname + \"/tmp_e_umd\", {\n"
"                method : \"GET\"\n"
"            }).then(r => {return r.json()}).then(r => {\n"
"                renderTMP(r.tmp, plantas,indice);\n"
"                renderUMD(r.umd, plantas, indice);\n"
"            })\n"
"        } , 2000);\n"
"    </script>\n"
"</html>\n";

void fornecer_pagina(String IP) {
  server.on("/", HTTP_GET, [html]() {
    server.send(200, "text/html", html);
  });
}